checker: fix fallout from QVector -> QList conversion, part II.
Qt5's QList doesn't support resize() yet, so it ends up with an error:
  XMLErrorRule.cpp:104:42: error: no matching function for call to 'QList<bool>::QList(const int&)'
     QList<bool> matchingFlags(numIncluded);

Fix this by using QVector as it makes more sense here.

Fixes: 422298c0937e ("all: use only QList, not QVector")