checker: fix fallout from QVector -> QList conversion
Qt6 doesn't care, but Qt5 does:
error: 'fromList' is not a member of 'QList<checker::SimpleAutomatonID>'

Fix this -- we need no more conversions.

Fixes: 422298c0937e ("all: use only QList, not QVector")